package com.example.springbootdemo.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Represents a review information including body.
 * This class is used to store the review information to the database
 * @author Zhikai Hu
 */
@Document(collection = "reviews")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Review {
    /**
     * We do not want to expose the id to the client. We would prefer imdbId to be the url
     */
    @Id
    private ObjectId id;

    /**
     * The body of the review
     */
    private String body;

    /**
     * This constructor is used to create a review
     * The id is auto-generated by the database
     * @param body the body of the review
     */
    public Review(String body) {
        this.body = body;
    }
}
